### PR TITLE
Reduce number of jobs for mesosdaq

### PR DESCRIPTION
**Pull request by TimoWilken**
QC PRs have out-of-memory errors, both in the O2 build and in some QC tests. 12 is too much, let's see if 10 works; hopefully we don't have to reduce it to 8 again.

### CODE REVIEW

**Comment by ktf** [comment]
Can you point me to one?

**Comment by TimoWilken** [comment]
https://github.com/AliceO2Group/QualityControl/pull/757

**Comment by ktf** [comment]
Is this correlated with bringing back alientest06 in business?

**Comment by TimoWilken** [comment]
I was mistaken earlier -- it was actually alientest02 where I changed the way mesos was run recently. Maybe taking mesos offline on alientest02 meant that one or two extra slc7 builders were scheduled on alientest06 and are taking up memory there, I'm not sure.

**Comment by ktf** [comment]
that should not happen, in the sense that mesos should avoid the resource overallocation. Can you check how many zombies you have on that machine?

**Comment by TimoWilken** [comment]
Mesos doesn't actually check that builders are only using their assigned 24G of memory and no more, IIRC. So if multiple builders go over that at the same time, that could cause problems.

There are quite a lot of zombies in some of the containers on that machine. I could restart those workers.

**Comment by ktf** [comment]
No, mesos / docker will actually enforce that. That's why they fail. It's not the global limit that we are passing, but the one in the container.

**Comment by ktf** [comment]
Regarding the zombies, in principle your cs8 changes should eliminate them, can we move to the new way of building stuff also for CC7?

**Pull request merged**
