### PR TITLE
Add a CI check in O2DPG

### PR DESCRIPTION
**Pull request by TimoWilken**
Build and check O2Suite (with O2 from dev and O2Physics from master) for PRs in O2DPG.

As requested at WP3 meeting.

### CODE REVIEW

**Comment by davidrohr** [comment]
What package will this test build? we should build o2-full-system-test.sh directly, not o2-fullci.

**Comment by TimoWilken** [comment]
I initially had it as only O2Suite, but I've changed it to O2-full-system-test now.

**Comment by TimoWilken** [comment]
In summary: the check will build O2-full-system-test with `o2` defaults against O2@dev and O2Physics@master, including their respective unit tests.

**Comment by davidrohr** [comment]
@TimoWilken : Sorry to bug again. we don't need the unit tests of O2/O2Physics. Can you disable them (Don't set ALIBUILT_O2_TESTS=1, as in the FullCI for O2)

**Pull request merged**
