### PR TITLE
Add CCDB-to-CVMFS caching script

### PR DESCRIPTION
**Pull request by TimoWilken**

### CODE REVIEW

**Comment by TimoWilken** [comment]
@grigoras @jgrosseo This is the CCDB-to-CVMFS caching script. It's tested and working (with `http://alice-ccdb.cern.ch/GLO/Param/MatLUT/1672531199000` as a test case, on CVMFS now). When merged, it'll run together with the package publisher every 15 minutes.

I'd suggest controlling what objects get cached using the `publish/cache-ccdb-objects.txt` file added by this PR in ali-bot. That's just a flat text file, with one CCDB URL per line. People could then send PRs to ali-bot to add URLs to that file.

Who should be the code owners of the `publish/cache-ccdb-objects.txt` file?

**Comment by jgrosseo** [comment]
Very nice - thanks!

The only addition I have is if we would allow comments after the ccdb urls in the text file. I.e. ignore all lines starting with # and everything after a # in any line. This may be helpful for tracking.

For the code owners you can add David (we may need to invite him to alisw), @sawenzel, Costin (also not in this repo), and @jgrosseo

**Comment by TimoWilken** [comment]
Thanks @jgrosseo, I'll do that. Comment lines already work, but not comments after URLs on the same line.

**Comment by TimoWilken** [comment]
I've created the @alisw/ccdb-cache-owners team to own the `publish/cache-ccdb-objects.txt` file, with the people you suggest @jgrosseo.

@ddobrigk you'll have to manually accept the invitation to the team since you weren't part of the alisw org before -- check your emails!

**Comment by TimoWilken** [comment]
Merged.

@alisw/ccdb-cache-owners: I've also added a simple CI check that runs on any PR that changes `publish/cache-ccdb-objects.txt`. It checks for the same assumptions that the caching script makes, so if it fails, the caching itself will likely fail.

**Pull request merged**
