### PR TITLE
Revert dropping aliswmod #903 #944

### PR DESCRIPTION
**Pull request by awegrzyn**
Unfortunately, the old RPM pickup new `aliswmod`, I thought all deps are fixed, but `aliswmod` is the exception. Let's revert it for the moment and find out how to do it in a clean way.

### CODE REVIEW

**Comment by awegrzyn** [comment]
@ktf Could you also please remove `RPMS/el7.x86_64/alisw-aliswmod-4-1.el7.x86_64.rpm` from S3?

**Comment by awegrzyn** [comment]
@TimoWilken could you help with merging this and making sure RPM builder pick this up?

**Comment by TimoWilken** [comment]
OK, merged. I've restarted the RPM builder as well.

**Comment by awegrzyn** [comment]
Reason for this revert
- As `aliswmod` version is not fixed on RPM level, old RPMs pick up new version as well
- `aliswmod` v4 tried to create `/bin` dir what resulted in transaction error

Instead that we should
- Drop entirely `aliswmod` for new "non-updatable" RPMs

**Comment by ktf** [comment]
Maybe we should simply rename the rpm to something else? I guess we do need the environment no?

**Comment by awegrzyn** [comment]
The environment is not needed for "non-updatable" RPMs.
For updatable RPMs we don't really want to for the moment as our packages break system tools, so it's better to set paths only once this is needed (eg. in ControlWorkflows).

**Comment by ktf** [comment]
How about we clean completely the template from the updatable RPMs and we have a separate template, just for those? I fear two many issues are related to trying to kill two pigeons with one stone.

**Comment by awegrzyn** [comment]
sure, I think it's very good idea

**Comment by awegrzyn** [comment]
@TimoWilken are you sure RPM builder uses new commit? An RPM that has been just created uses `RPMS/el7.x86_64/alisw-aliswmod-4-1.el7.x86_64.rpm`.

**Comment by TimoWilken** [comment]
The rpm_creation task has ali-bot 30a2c29, so it's got the changes from this PR. Could that be a leftover from before I restarted it?

**Comment by awegrzyn** [comment]
ok thanks, idk, but we just need to make sure that `aliswmod-4` does not get produced.

**Comment by vascobarroso** [comment]
@TimoWilken @ktf please treat this as high priority, it is currently blocking us from progressing with the preparations for MW2.

**Comment by ktf** [comment]
`aliswmod-4` is not being produced. I guess this is a leftover from the previous runs? The new one is called `aliswmod4`

**Comment by ktf** [comment]
@vascobarroso it is top priority.

**Comment by vascobarroso** [comment]
@ktf great, thanks a lot for the support 👍

**Comment by ktf** [comment]
I love the smell of code when it gets deleted.

**Pull request merged**
