### PR TITLE
Reduce JOBS to 6 in CI and Jenkins builds

### PR DESCRIPTION
**Pull request by TimoWilken**
This is to avoid the compiler segfaults.

### CODE REVIEW

**Comment by ktf** [comment]
It says 10...

**Comment by TimoWilken** [comment]
I've fixed the title!

**Comment by davidrohr** [comment]
Does this really fix the compiler segfault? A segfault is usually not triggered by too little memory.

**Comment by ktf** [comment]
I did not realise it was a segfault. Indeed we should try to understand what is going on...

**Pull request closed without merging**
