### PR TITLE
cleanup macOS CI config files

### PR DESCRIPTION
**Pull request by MichaelLettrich**
Cleanup the different configurations for the macOS CI to reflect the current situation of the CI.

### CODE REVIEW

**Comment by MichaelLettrich** [comment]
asking for review because I would like to adapt the naming scheme of the tests - please comment.

**Comment by ktf** [comment]
@MichaelLettrich are you still working on this?

**Comment by MichaelLettrich** [comment]
Will do some tests this weekend and plan to merge on monday

**Comment by MichaelLettrich** [comment]
@ktf  can we merge this?

**Pull request merged**
