### PR TITLE
Document setup of a CVMFS software namespace

### PR DESCRIPTION
**Pull request by dberzano**
* aliPublish documentation
* CVMFS alienv documentation
* Simple aliPublish example configuration

### CODE REVIEW

**Comment by dberzano** [comment]
@rjefferson for your consideration. You can see the full documentation [here](https://github.com/dberzano/ali-bot/tree/alipublish-doc/publish). We'll merge it based on your feedback :-)

**Comment by ktf** [comment]
@dberzano can we merge this?

**Comment by dberzano** [comment]
I am still waiting for @rjefferson's feedback (he should be around this week and have a look at it).

**Comment by rjefferson** [comment]
yes - I haven't had a chance to review it.  Am doing so today & should answer later today or tomorrow

**Comment by rjefferson** [comment]
I was able to add a Cori variant (aliPublisher & if block in 'get-and-run.sh') and run the build from my repository.  It seems to work - albeit that my test was fake as Cori is down for maintenance.  I think I can develop from this & probably simplify into a generic type of publisher instead of a 'titan' or 'cori' variant.    Please go ahead and merge.

**Pull request merged**
