### PR TITLE
Add CVMFS alienv support for latest Ubuntu/Debian

### PR DESCRIPTION
**Pull request by dberzano**
* Add `MODULES_USE_COMPAT_VERSION` in case system's modulecmd is too recent
* Add `$moduleenv` where missing

### CODE REVIEW

**Comment by mimarpe** [comment]
No more warnings anymore @dberzano :-) thanks!

**Comment by mimarpe** [comment]
mmmartin@pcalice92:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 17.10
Release:        17.10
Codename:       artful
mmmartin@pcalice92:~$ /cvmfs/alice-nightlies.cern.ch/bin/alienv checkenv VO_ALICE@AliPhysics::v5-09-27-01-rc2-1,VO_ALICE@AliRoot::v5-09-27-rc2-1
mmmartin@pcalice92:~$ echo $?
0

**Comment by dberzano** [comment]
@mimarpe ok but this is another problem, right?

**Comment by dberzano** [comment]
Or not, actually it's correct.

**Pull request merged**
