### PR TITLE
Upgrade CI builders to alibuild 1.6.5

### PR DESCRIPTION
**Pull request by TimoWilken**
To fix [O2-1926](https://alice.its.cern.ch/jira/browse/O2-1926).

### CODE REVIEW

**Comment by ktf** [comment]
Can we try with one, before we do for all?

**Comment by TimoWilken** [comment]
I've deployed it to build/mesosci/prod/ci_alisw_slc7-builder_latest/0, and it's rebuilt e.g. [alidist #2698 build/O2/alidist-dataflow](https://ali-ci.cern.ch/alice-build-logs/alisw/alidist/2698/9a389916625441765fa66ead8b9a89838af9548e/build_O2_alidist-dataflow/pretty.html) successfully so far. I'll check it again tomorrow morning.

**Comment by TimoWilken** [comment]
The problem is still there for some builds:
```
2020-12-18@05:09:16:DEBUG:AliRoot:AliRoot:build_AliRoot_alidist: ++ source /mnt/mesos/sandbox/sandbox/aliroot-alidist/sw/slc7_x86-64/GEANT4/v10.4.2-1/etc/profile.d/init.sh
2020-12-18@05:09:16:DEBUG:AliRoot:AliRoot:build_AliRoot_alidist: /mnt/mesos/sandbox/sandbox/aliroot-alidist/sw/slc7_x86-64/GEANT4_VMC/v3-6-p6-inclxx-biasing-p2-1/etc/profile.d/init.sh: line 2: /mnt/mesos/sandbox/sandbox/aliroot-alidist/sw/slc7_x86-64/GEANT4/v10.4.2-1/etc/profile.d/init.sh: No such file or directory
```
The following exist in the store:
```
-rw-r--r-- 1 root root 820M Dec 17 22:04 TARS/slc7_x86-64/store/1b/1b9dc10a172898ebf8d8871202e76556a1841b92/GEANT4-v10.4.2-1.slc7_x86-64.tar.gz
-rw-r--r-- 1 root root 820M Dec 18 06:52 TARS/slc7_x86-64/store/1b/1b9dc10a172898ebf8d8871202e76556a1841b92/GEANT4-v10.4.2-30.slc7_x86-64.tar.gz
-rw-r--r-- 1 root root 820M Dec 17 21:45 TARS/slc7_x86-64/store/87/872922e466dafc6d067b49c2ec1610da4f260003/GEANT4-v10.4.2-1.slc7_x86-64.tar.gz
-rw-r--r-- 1 root root 820M Dec 18 07:33 TARS/slc7_x86-64/store/87/872922e466dafc6d067b49c2ec1610da4f260003/GEANT4-v10.4.2-29.slc7_x86-64.tar.gz
-rw-r--r-- 1 root root  14M Dec 16 21:08 TARS/slc7_x86-64/store/c9/c9334586ad240c778fe2a2db39aa77200991913d/GEANT4_VMC-v3-6-p6-inclxx-biasing-p2-1.slc7_x86-64.tar.gz
```
but in `TARS/slc7_x86-64/GEANT4`, only the following symlinks' targets exist:
```
lrwxrwxrwx 1 root root 104 Dec 18 07:33 GEANT4-v10.4.2-29.slc7_x86-64.tar.gz -> ../../slc7_x86-64/store/87/872922e466dafc6d067b49c2ec1610da4f260003/GEANT4-v10.4.2-29.slc7_x86-64.tar.gz
lrwxrwxrwx 1 root root 104 Dec 18 06:52 GEANT4-v10.4.2-30.slc7_x86-64.tar.gz -> ../../slc7_x86-64/store/1b/1b9dc10a172898ebf8d8871202e76556a1841b92/GEANT4-v10.4.2-30.slc7_x86-64.tar.gz
```
but the following symlink points to a nonexistent file:
```
lrwxrwxrwx 1 root root 103 Dec 18 07:32 GEANT4-v10.4.2-1.slc7_x86-64.tar.gz -> ../../slc7_x86-64/store/08/08442a119030b672a7c07e055d1a942c5d936639/GEANT4-v10.4.2-1.slc7_x86-64.tar.gz
```
Only v10.4.2-29 is installed in `slc7_x86-64/GEANT4`:
```
lrwxrwxrwx 1 root root   10 Dec 18 07:33 latest -> v10.4.2-29
lrwxrwxrwx 1 root root   10 Dec 18 07:33 latest-build_AliRoot_alidist-prod-latest -> v10.4.2-29
drwxr-xr-x 7 root root 4096 Dec 12 20:06 v10.4.2-29
```

I've restarted the builder to see if that fixes it. I didn't restart it after installing alibuild 1.6.5.

**Comment by ktf** [comment]
Indeed a restart might be needed to bring things back working state.

**Pull request merged**
