### PR TITLE
Allow optional letter in O2DPG version

### PR DESCRIPTION
**Pull request by TimoWilken**
To enable multiple releases per day, but avoiding incrementing the number (as that would be confusing if the number is the day almost everywhere else).

### CODE REVIEW

**Comment by ktf** [comment]
@TimoWilken who requested this change?

**Review by ktf — COMMENTED** [review]
Who is requesting for this change?

**Comment by TimoWilken** [comment]
@sawenzel is.

**Comment by ktf** [comment]
Fine with me, but I guess @chiarazampolli and @fprino need to agree as well.

**Comment by chiarazampolli** [comment]
Nothing against it from my side!

**Comment by fprino** [comment]
It is fine also with me.

**Pull request merged**
