### PR TITLE
Create DEFAULT.env

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
Looks like you need one in any case...

**Comment by ktf** [comment]
@TimoWilken

**Comment by TimoWilken** [comment]
It's not required but gets sourced if it exists (note the `|| true`):

```bash
      . ali-bot/ci/repo-config/DEFAULTS.env                              || true
      . "ali-bot/ci/repo-config/$MESOS_ROLE/DEFAULTS.env"                || true
      . "ali-bot/ci/repo-config/$MESOS_ROLE/$cur_container/DEFAULTS.env" || true
      . "$env_file"                                                      || exit
```

**Comment by ktf** [comment]
ah, ok. Maybe you should check for the file to exists? Something like:

```
[ -f "ali-bot/ci/repo-config/$MESOS_ROLE/DEFAULTS.env" ] && . "ali-bot/ci/repo-config/$MESOS_ROLE/DEFAULTS.env"
```

?

**Pull request merged**
