### PR TITLE
Update run-all-rpms.sh

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@TimoWilken could you please verify this works and deploy?

**Comment by TimoWilken** [comment]
@ktf Works for me. I can deploy once the PR is merged.

Just a suggestion: if `--progress` is too much output, `--verbose` might be an option too? It gives some feedback but not as much as `--progress`.

**Comment by ktf** [comment]
Good idea. --verbose is fine.

**Comment by ktf** [comment]
Can you change and deploy?

**Comment by TimoWilken** [comment]
I've pushed the change to `--verbose`. I've deployed it using the PR branch for now, I'll change it back to master once the PR is merged.

**Pull request merged**
