### PR TITLE
Test QC-dataflow against O2 dev branch

### PR DESCRIPTION
**Pull request by TimoWilken**
This brings build/QualityControl/o2-dataflow in line with build/QualityControl/o2, which is already tested against O2@dev.

### CODE REVIEW

**Comment by TimoWilken** [comment]
@davidrohr @Barthelemy I don't know if you're the right people to ask about this, but what about Configuration, InfoLogger, Monitoring and ReadoutCard? Should they be tested against O2@dev too?

**Comment by davidrohr** [comment]
Could you do the same for the o2-dataflow test of QC on MacOS?

**Comment by TimoWilken** [comment]
@davidrohr done, thanks for the reminder!

**Comment by davidrohr** [comment]
> @davidrohr @Barthelemy I don't know if you're the right people to ask about this, but what about Configuration, InfoLogger, Monitoring and ReadoutCard? Should they be tested against O2@dev too?

Personally I would say yes. @ktf @sawenzel  : What do you think? Perhaps we should discuss this in WP3?

**Comment by Barthelemy** [comment]
I agree, it should be raised in WP3. @ihrivnac

**Comment by Barthelemy** [comment]
@TimoWilken Thank you very much for taking care of the QC tests

**Comment by ihrivnac** [comment]
> I agree, it should be raised in WP3. @ihrivnac

The agenda for the next WP3 meeting is now available at: https://indico.cern.ch/event/999182/
Please, add a discussion item in the document.

**Comment by TimoWilken** [comment]
Thanks @ihrivnac, I've added a discussion item.

**Comment by davidrohr** [comment]
@TimoWilken : Why does the CI fail here? I'd like to merge this to fix the failures in the QC CI.

**Comment by TimoWilken** [comment]
@davidrohr it needs some packages installed, #932 should fix it. When that's merged, I can rebase on top of that.

The CI doesn't check the .env files at all, though, so it shouldn't affect it in this case.

**Comment by TimoWilken** [comment]
@davidrohr rebased, checks are green now.

**Pull request merged**
