### PR TITLE
Remove cs8 builders

### PR DESCRIPTION
**Pull request by singiamtel**
Not used anymore

As discussed over coffee break with @ktf @davidrohr 

**They have to be removed as required checks before merging**

### CODE REVIEW

**Comment by Barthelemy** [comment]
Hi, 

Could you give me a bit of context ? 

Thankyou

**Comment by Barthelemy** [comment]
The whole FLP farm is on CS8 and we are not sure we are going to move to alma 9 because there is a severe issue with PDA and we depend on other people to fix it. 

In QualityControl we use `o2-dataflow-cs8` and `o2-cs8`. 

I would not remove them until we know that we are moving to alma 9 or rhel 9 in the FLP farm. Otherwise we are not testing on the systems we are running onto.

**Comment by ktf** [comment]
Ok, fair enough. @singiamtel let's keep anything which includes QC / dataflow to cs8, then.

**Comment by davidrohr** [comment]
Hi Barth, just for my understanding: I thought FLPs use the dataflow defaults. How are you using both o2 and o2-dataflow defaults for QC then?

Kind Regards
David Rohr

**Comment by Barthelemy** [comment]
@davidrohr good point. Actually we run on both FLPs and EPNs and thus it must be tested on both CS8 and Alma 9. I propose to keep o2-dataflow-cs8 on CS8 and have o2-cs8 on Alma.

**Comment by davidrohr** [comment]
EPNs run a different build that is tested in the FullCI already.

Kind Regards
David Rohr

**Comment by Barthelemy** [comment]
ok, so you are saying that `QualityControl/O2fst/o2` running on Alma 9 + `build/QualityControl/o2-dataflow-cs8 ` on CS8 is enough ?

**Comment by davidrohr** [comment]
Yes, except that currently fst is still on alma8 and we will move to alma9 when epns move to alma9.

Kind Regards
David Rohr

**Comment by Barthelemy** [comment]
ok, then it sounds good. @singiamtel could you update this pr accordingingly ?
Thank you

**Comment by davidrohr** [comment]
> * build/QualityControl/O2fst/o2 -> **Migrated from slc7 to slc9**

Isn't the current fst build on the slc8-gpu-builder container?

**Comment by davidrohr** [comment]
Right now, the EPNs are on ALMA8, so all FullCI / FST builders should run with the slc8-gpu-builder.
So we should switch the qualitycontrol/fst from slc7 to slc8-gpu-builder.

And we remove all the -cs8 builders (not the -cs8-dataflow) to get some free resources.

In the next step, for preparing the EPNs for ALMA9, we have to duplicate all FullCI/FST builders in AliceO2 / QC / alidist from slc8-gpu-builder to slc9-gpu-builder.
And then, once EPNs are migrated, we will remove all old builders using slc8-gpu-builder container.

**Comment by Barthelemy** [comment]
ok for me with the following

1. build_O2_Common -> cs8 
2. build_QualityControl_o2 -> cs8
3. build_QualityControl_o2-dataflow-cs8 -> no change
4. build_QualityControl_O2fst_o2 -> cs8
5. build_QualityControl_o2-cs8 -> Remove

Thank you Sergio

**Comment by ktf** [comment]
Looks good. Please go ahead and merge both PRs.

**Pull request merged**
