### PR TITLE
Publish test AliGenerators on nightlies

### PR DESCRIPTION
**Pull request by dberzano**

### CODE REVIEW

**Comment by dberzano** [comment]
@qgp you'll get emails when AliGenerators is updated on CVMFS and nightlies. Do you need to be notified for other sensible packages?

**Comment by qgp** [comment]
Fine for now, I think. But would you mind adding also Redmer? Thanks!

**Comment by dberzano** [comment]
Done

**Comment by qgp** [comment]
Perfect, thnx!

**Pull request merged**
