### PR TITLE
Implement required changes for O2PDPSuite release process

### PR DESCRIPTION
**Pull request by TimoWilken**
This is a draft of the reworked implementation, as requested by @ktf. This also requires changes to aliBuild.

- allow templating in AUTOTAG_PATTERN (date formatting is done afterwards)
- allow overriding specific packages' tags

Cc: @davidrohr

### CODE REVIEW

**Review by davidrohr — DISMISSED** [review]
seems OK in the weekly build from today

**Comment by TimoWilken** [comment]
In that case, I'm happy with it too.

**Comment by TimoWilken** [comment]
716e90bb197d05a742667a14b17d4f82d21d1d49 implements one more feature @ktf asked for, namely that QC should be tagged, but not included in the final alidist commit. This seems like the easiest place to put this as well; I hope that's alright.

**Comment by ktf** [comment]
Are we ready to merge this?

**Comment by TimoWilken** [comment]
Fine by me! I can check it ran correctly tomorrow morning.

**Comment by ktf** [comment]
Do we need to change the jenkins rule for this to work?

**Comment by TimoWilken** [comment]
I don't think so. There are only a few additional env vars, but if they're not declared as parameters, they'll just be unset, which is fine.

**Pull request merged**
