### PR TITLE
Do not hardcode updatable RPMs version (O2-1360)

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@awegrzyn @Barthelemy I assume this should be the wanted behaviour, correct? Do you see any case were this would not be the case for the updatable RPMs?

**Comment by awegrzyn** [comment]
@ktf After quick look it's fine by me, but I think we shall discuss it within FLP project

**Comment by ktf** [comment]
Ok. Let me know.

**Comment by ktf** [comment]
Ping?

**Comment by awegrzyn** [comment]
Hi, we have scheduled meeting tomorrow at 10 to discuss that

**Comment by awegrzyn** [comment]
@ktf It's good to go

**Comment by awegrzyn** [comment]
@ktf I recreated RPMs yesterday, but they still use `=` instead of `>=`

**Comment by ktf** [comment]
Mmmm... I might have to redeploy. :-/ Let me check.

**Comment by ktf** [comment]
Yes, sorry about that. Can you try again?

**Pull request merged**
