### PR TITLE
Publish RPM for FLPSuiteDevEnv

### PR DESCRIPTION
**Pull request by Barthelemy**

### CODE REVIEW

**Review by ktf — DISMISSED** [review]

**Comment by Barthelemy** [comment]
I don't understand the error.

**Comment by TimoWilken** [comment]
GitHub upgraded `ubuntu-latest` containers from 18.04 to 20.04 (IIRC) recently. I assume it's now using python3 by default instead of python2. The easiest solution is probably to adjust aliPublish's shebang to `#!/usr/bin/env python2`.

**Comment by ktf** [comment]
Indeed. Done in #1010.

**Comment by ktf** [comment]
https://alice.its.cern.ch/jira/browse/O2-2260 for the rest...

**Comment by ktf** [comment]
Fixed by #1011

**Pull request closed without merging**
