### PR TITLE
alienv: add el7 and optionally override CVMFS dir

### PR DESCRIPTION
**Pull request by dberzano**
* Enable RedHat 7 among the list of preferred platforms
* Optionally override default CVMFS dir using ALIENV_CVMFSDIR

### CODE REVIEW

**Comment by dberzano** [comment]
@ktf the "el7" part makes mesos work from CVMFS. I have tested this PR.

**Comment by dberzano** [comment]
@ktf yes as discussed privately doc is already here on GitHub. The part of "adding new archs" inside `alienv` is missing, I am going to add it to this PR.

We can even have it automatically finding archs, I just fear that something can go wrong due to the deployment scale of this tiny script!

**Comment by ktf** [comment]
Given we have three archs and probably the next one is coming in a few years, I agree to play it safe for now...

**Comment by ktf** [comment]
Thanks!

**Comment by dberzano** [comment]
Thanks to you for the comments!

**Pull request merged**
