### PR TITLE
Expose CI_NAME and CHECK_NAME

### PR DESCRIPTION
**Pull request by ktf**
The idea is to use them to select which checks to run.

### CODE REVIEW

**Comment by ktf** [comment]
@TimoWilken what do you think of this?
@Barthelemy this is what we discussed on mattermost.

**Comment by TimoWilken** [comment]
I suppose this ought to work. Where would these vars be used -- in alidist recipes?

**Comment by Barthelemy** [comment]
yes in alidist recipes. In the QC in particular I would like that some tests are only run in the tests in the QC repo and not in alidist.

**Comment by TimoWilken** [comment]
Fair enough. Would exporting `PR_REPO` be a better fit in that case? That always contains the repo name in `organization/repository` format that we are running the check for, whereas `CI_NAME` and `CHECK_NAME` are intended to be more human-readable and can be a bit more free-form.

**Comment by ktf** [comment]
Ok, let's do the full monty, then... Maybe we could switch off some tests based on the branch, for the future where we have both dev and master.

**Comment by TimoWilken** [comment]
One thing I forgot -- you should give these vars to `aliBuild build` explicitly using an `-e "ALIBOT_PR_REPO=$PR_REPO"` option for each one, otherwise they won't be propagated into the build Docker container. Then you also don't need the `export ...` lines.

**Comment by ktf** [comment]
Updated with @TimoWilken suggestions.

**Comment by Barthelemy** [comment]
could we go ahead with this ?

**Comment by ktf** [comment]
@TimoWilken could you redeploy the builders with this, at your convenience?

**Comment by TimoWilken** [comment]
The builders auto-update to the master branch of ali-bot, so it'll happen gradually as they finish their in-progress builds.

**Pull request merged**
