### PR TITLE
Use alibuild's docker support for CI

### PR DESCRIPTION
**Pull request by TimoWilken**
See commits for individual changes.

### CODE REVIEW

**Comment by ktf** [comment]
There is a few conflicting files. Could you check?

**Comment by TimoWilken** [comment]
I've rebased now!

**Comment by ktf** [comment]
What is missing here?

**Comment by TimoWilken** [comment]
Nothing is missing, I'd just like to hold off on merging this until I've installed mesos on alientest06. Until then, there isn't enough capacity to switch over the slc7 builders.

**Comment by TimoWilken** [comment]
I've rebased on master.

I also added some fixes to make this work on MacOS, and all remaining slc7 builders have been moved over to this code, so this is ready to be reviewed and merged.

**Review by ktf — APPROVED** [review]
OK to merge. Please make sure you do so when you are sure you can be around to handle the fallout.

**Pull request merged**
