### PR TITLE
Publish one-off releases for AliRoot

### PR DESCRIPTION
**Pull request by TimoWilken**
Needed for https://alice.its.cern.ch/jira/browse/ALIROOT-8707.

@ktf, is this the correct file for lxplus/Grid publishing or do I need to add it elsewhere?

### CODE REVIEW

**Comment by ktf** [comment]
I wouldnt call it like that. Where was this discussed?

**Comment by TimoWilken** [comment]
Nowhere, I just made that up. Any preference for how it should be called?

**Comment by TimoWilken** [comment]
Updated with the new naming convention.

I've published new tags in [AliRoot] and [alidist], and removed the old `JIRA-*` tags (including in AliPhysics).

[AliRoot]: https://github.com/alisw/AliRoot/releases/tag/v5-10-01-test-hepmc-1
[alidist]: https://github.com/alisw/alidist/releases/tag/AliRoot-v5-10-01-test-hepmc-1

**Comment by ktf** [comment]
Mmm, no we should keep the 09 part, not move it to 10.

**Comment by TimoWilken** [comment]
What minor number are we on, then? `v5-09-01-test-hepmc-1`? `v5-09-58-test-hepmc-1`? We're not on any `v5-09-*-patches` branch.

**Comment by TimoWilken** [comment]
Not needed. I changed the alidist commit to only change AliRoot's version number, and to build with the then-current AliPhysics release, so the testing release was published anyway.

**Pull request closed without merging**
