### PR TITLE
Use O2 daily tags in dataflow CI check

### PR DESCRIPTION
**Pull request by awegrzyn**
This is to make sure that QC RPMs are built correctly.
Currently if QC uses features from dev the RPM compilation may fail as it uses tag from O2 recipe.

### CODE REVIEW

**Comment by awegrzyn** [comment]
@Barthelemy could you confirm?

**Comment by ktf** [comment]
Ping @Barthelemy

**Review by Barthelemy — APPROVED** [review]

**Comment by Barthelemy** [comment]
everything fails ? are we waiting for something else ?

**Comment by TimoWilken** [comment]
CI errors are unrelated, #1021 should fix those. The files this PR changes aren't tested by these checks anyway.

**Pull request merged**
