### PR TITLE
Use S3 repo by default in daily-tags.sh

### PR DESCRIPTION
**Pull request by TimoWilken**

### CODE REVIEW

**Comment by ktf** [comment]
Before we can do this, we need to make sure we can publish to CVMFS from S3.

**Comment by TimoWilken** [comment]
OK! How do we do that?

**Comment by ktf** [comment]
Currently the publishing is happening via `ali-bot/publisher`. What it does it's to query ali-ci.cern.ch to get the list of packages to be published. We need to adapt from the JSON based package list which we have there to the flat one returned by S3.

**Comment by TimoWilken** [comment]
For aliPublish changes, see: #921

**Comment by ktf** [comment]
We need to rethink this before it can be merged. As we need to make sure that the old (cc7) repository is fully consistent in S3 and can be used.

**Pull request closed without merging**
