### PR TITLE
Publish RPMs on CentOS 8

### PR DESCRIPTION
**Pull request by TimoWilken**
Publish the same things on CC8 as on CC7.

### CODE REVIEW

**Comment by davidrohr** [comment]
@TimoWilken : How are the CC8 RPMs built? Inside the slc8-builder, or the slc8-gpu-builder?
We need the latter, to have the GPU part built for the EPNs.

**Comment by TimoWilken** [comment]
@davidrohr currently they're built on plain slc8. Thanks for the heads-up, I'll talk to Giulio tomorrow to work out a good way to build on slc8-gpu instead!

**Comment by ktf** [comment]
I would just use the slc8-gpu-builder image. What is stopping us from doing so?

**Comment by TimoWilken** [comment]
Is it OK if all the slc8 Jenkins builds run on slc8-gpu? If so, that makes things a bit simpler.

**Comment by ktf** [comment]
yes. That's fine.

**Comment by TimoWilken** [comment]
Great, done!

**Comment by TimoWilken** [comment]
Thanks! I'll restart the rpm_creation task so it picks up these changes.

**Pull request merged**
